### ISSUE TITLE
Correcting the name in the frontend 

### ISSUE THREAD

**Issue by Eeshu-Yadav** [bhyeanhasan/Image-Editor-using-Django#1]
![Screenshot 2024-10-04 164141](https://github.com/user-attachments/assets/ef207f3c-c56f-4d5b-86c4-adef72c8cf21)
in this the name of canvas is incorrect . i know that is not major issue but i can correct it.

**Comment by Eeshu-Yadav** [comment]
@bhyeanhasan can you assign it to me?

**Comment by bhyeanhasan** [comment]
Yes, You can do it, just give a pr request

**Comment by Eeshu-Yadav** [comment]
@bhyeanhasan label it with hacktoberfest 2024

**Comment by Eeshu-Yadav** [comment]
@bhyeanhasan  i can contribute to your project . can you label them with tag of hacktober like this one.

![Screenshot 2024-10-07 150045](https://github.com/user-attachments/assets/f1dfea40-101e-4767-a594-e6d5322918d5)
